"""merged checkin table with registration table

Revision ID: 4d1052806fec
Revises: e5b5889fa389
Create Date: 2018-08-17 17:46:22.106435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d1052806fec'
down_revision = 'e5b5889fa389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkin')
    op.add_column('registrations', sa.Column('checked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'checked_at')
    op.create_table('checkin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('checked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('checked_in', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('register_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['register_id'], ['registrations.id'], name='checkin_register_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='checkin_pkey')
    )
    # ### end Alembic commands ###
