"""added faculty field

Revision ID: 730430f7fe7e
Revises: dc378ffad29e
Create Date: 2018-08-17 17:09:23.599237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730430f7fe7e'
down_revision = 'dc378ffad29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('faculty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'faculty')
    # ### end Alembic commands ###
