"""added timezone to registration and checkin models

Revision ID: 80e3c0492e0b
Revises: effed2e18cc9
Create Date: 2018-11-11 12:18:04.572030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e3c0492e0b'
down_revision = 'effed2e18cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registrations', 'registered_at', type_=sa.DateTime(timezone=True))
    op.alter_column('checkins', 'checked_at', type_=sa.DateTime(timezone=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registrations', 'registered_at', type_=sa.DateTime(timezone=False))
    op.alter_column('checkins', 'checked_at', type_=sa.DateTime(timezone=False))
    # ### end Alembic commands ###
