"""added badge field to the registration

Revision ID: 8c55a1285df2
Revises: 80e3c0492e0b
Create Date: 2019-11-18 08:49:56.355568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c55a1285df2'
down_revision = '80e3c0492e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('badge', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'badge')
    # ### end Alembic commands ###
