"""added academic title

Revision ID: 99ddda7e91ae
Revises: ed22d507601d
Create Date: 2025-11-12 18:55:08.629868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ddda7e91ae'
down_revision = 'ed22d507601d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_title', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_column('academic_title')

    # ### end Alembic commands ###
