"""maded the participant ID autoincremental

Revision ID: c96450ab3cfb
Revises: f868c978334b
Create Date: 2018-10-06 07:28:11.179950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence


# revision identifiers, used by Alembic.
revision = 'c96450ab3cfb'
down_revision = 'f868c978334b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('participants_id_seq')))
    op.alter_column("participants", "id", nullable=False, server_default=sa.text("nextval('participants_id_seq'::regclass)"))
    op.alter_column('participants', 'email', nullable=False)
    op.alter_column('participants', 'firstname', nullable=False)
    op.alter_column('participants', 'lastname', nullable=False)
    op.add_column('participants', sa.Column('old_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'id', autoincrement=False)
    op.alter_column('participants', 'email', nullable=True)
    op.alter_column('participants', 'firstname', nullable=True)
    op.alter_column('participants', 'lastname', nullable=True)
    op.drop_column('participants', 'old_id')
    # ### end Alembic commands ###
