"""added foreignkey to register table

Revision ID: d7756540e297
Revises: 730430f7fe7e
Create Date: 2018-08-17 17:40:25.985068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7756540e297'
down_revision = '730430f7fe7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('participant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'registrations', 'participants', ['participant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_column('registrations', 'participant_id')
    # ### end Alembic commands ###
