"""added foreignkey to checkin table

Revision ID: e5b5889fa389
Revises: d7756540e297
Create Date: 2018-08-17 17:43:01.497761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b5889fa389'
down_revision = 'd7756540e297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkin', sa.Column('register_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'checkin', 'registrations', ['register_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checkin', type_='foreignkey')
    op.drop_column('checkin', 'register_id')
    # ### end Alembic commands ###
