"""added attend-as field

Revision ID: ed22d507601d
Revises: 39bf102fc379
Create Date: 2019-11-18 09:21:55.061434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed22d507601d'
down_revision = '39bf102fc379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('attend_as', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'attend_as')
    # ### end Alembic commands ###
