"""removed checked_at from the registrations table

Revision ID: effed2e18cc9
Revises: 4376549bc799
Create Date: 2018-11-05 09:25:33.071288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'effed2e18cc9'
down_revision = '4376549bc799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('reg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reg_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('registrations', 'checked_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('checked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_table('checkins')
    # ### end Alembic commands ###
