"""added role table and relationship

Revision ID: f868c978334b
Revises: 8a8261fb4f7a
Create Date: 2018-10-06 04:11:27.813314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f868c978334b'
down_revision = '8a8261fb4f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('participants', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participants', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.drop_column('participants', 'role_id')
    op.drop_table('roles')
    # ### end Alembic commands ###
