version: '3'

services:
  pg:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5436:5432"
  web:
    build: .
    command: gunicorn --workers=5 --threads=12 --bind 0.0.0.0:5000 app.main:app
    environment:
      - FLASK_APP=/app/main.py
      - FLASK_DEBUG
      - SECRET_KEY
      - MAIL_PASSWORD
    volumes:
      - ./app:/app
    ports:
      - "5550:5000"
      - "80:5000"
    depends_on:
      - pg

volumes:
  pg_data:
