version: '3'

services:
  pg:
    image: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
    ports:
      - "5436:5432"
  web:
    build: .
    command: flask run -h 0.0.0.0 -p 5000
    environment:
      - FLASK_APP=/app/main.py
      - FLASK_DEBUG=1
      - MAIL_PASSWORD=$MAIL_PASSWORD
    volumes:
      - ./app:/app
    ports:
      - "5550:5000"
    depends_on:
      - pg

volumes:
  pg_data:
