version: '3'

services:
  pg:
    image: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
    ports:
      - "5436:5432"
  web:
    build: .
    command: python main.py
    environment:
      - FLASK_APP=/app/main.py
      - DEBUG=1
    volumes:
      - ./app:/app
    ports:
      - "5550:5000"
    depends_on:
      - pg

volumes:
  pg_data:
